### ISSUE TITLE
✅ Update translations for the app.

### ISSUE THREAD

**Issue by alexmercerind** [alexmercerind/harmonoid#15]
👋 Hello everyone,

@raitonoberu 
@mytja 
@bdlukaa 
@MickLesk

**I'm hereby requesting everyone to please review the translations for the app once again and make sure that you don't leave any string untranslated & take care of things like capitalization of letters etc. I have added some new strings according to requirement of new features.**

📃 [Here](https://github.com/alexmercerind/harmonoid/blob/master/lib/scripts/globalsupdater.dart) is the file.

A new pre-release(🎉 v0.0.2) with many new exciting features, big performance improvements & bug-fixes is just on the edge to arrive. Before I compile it, please review your respective languages 🐱‍💻.

I also wanna say that, please don't remove/add whitespaces. Only modify the string values.

**Progress**
- [x] English
- [x] Russian
- [x] Slovenian
- [x] Hindi
- [ ] Portuguese 
- [ ] German

Thanks a lot for your awesome support ❤

**Comment by mytja** [comment]
My translantion will be done today (probably), but I won't translate German, since, @MickLesk will probably do it!

**Comment by MickLesk** [comment]
I then check the translation again. I am German, translated directly at the live example. Think everything should be right. :-)

**Comment by raitonoberu** [comment]
Before I start... I'm not sure that this is possible, but if so, could you take screenshots of these lines in English? I'm in a bit of doubt about a few lines. (e.g. I can translate "saved" as "сохранённые" (plural participle) or "сохранено" (means "saved successfully"))
Thanks!

**Comment by alexmercerind** [comment]
Hi @raitonoberu, 
"Saved" is a string used to indicate two things:
- Track is already saved on the device.
- Downloading is completed.  

Sorry for delay I added two more strings for a feature.

Screenshot for your reference:
![Screenshot_20200907-184644](https://user-images.githubusercontent.com/28951144/92391698-c395e800-f13a-11ea-8f99-d8692a4dcc57.jpg)

**Comment by raitonoberu** [comment]
👌 #16

**Comment by mytja** [comment]
#17 
My update is prepeared. :rocket:
BTW, amazing UI

**Comment by alexmercerind** [comment]
Hi @raitonoberu & @mytja !
👌 You can download & try out the new release!

**Download: [APK](https://github.com/alexmercerind/harmonoid/releases/download/v0.0.2/harmonoid-v0.0.2-pre-release.apk)**
**Changelog: [Link](https://github.com/alexmercerind/harmonoid/releases/tag/v0.0.2)**

Thankyou for your support ❤!
I hope you will like this release.

**Comment by alexmercerind** [comment]
I cleared some of the comments to avoid scrolling down to bottom.

**Comment by raitonoberu** [comment]
Mate, I... I have no words. Your app has just become my favorite music app. Absolutely everything looks beautiful and works like clockwork😍! You've done a great job!

**Comment by alexmercerind** [comment]
@raitonoberu, I'm glad you liked the app. But this few really serious bugs, I didn't see during testing. I should probably amend those.

**Comment by mytja** [comment]
I also have no words.
Amazing UI, awesome search. Best music app ever.
But harmonoid-service.herokuapp.com is currently offline or blocked.

**Comment by alexmercerind** [comment]
@mytja . You can use http://harmonoid-ru.herokuapp.com meanwhile. I seriously don't know what is going wrong.

I have to talk to @raitonoberu.

**Comment by raitonoberu** [comment]
Try `harmonoidservice.herokuapp.com!

**Comment by alexmercerind** [comment]
Hey @raitonoberu,

I kinda need your help.
I just tried your server & it is working fine. But my server (both harmonoid & harmonoidservice) is giving errors like this:
```
2020-09-08T03:44:18.627862+00:00 app[web.1]: 106.215.253.102:0 - "GET /trackdownload?track_id=3pQLMqRn_pw&album_id=MPREb_cK4MowB5Oy6 HTTP/1.1" 500
2020-09-08T03:44:18.628900+00:00 app[web.1]: [2020-09-08 03:44:18 +0000] [10] [ERROR] Exception in ASGI application
2020-09-08T03:44:18.628902+00:00 app[web.1]: Traceback (most recent call last):
2020-09-08T03:44:18.628903+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
2020-09-08T03:44:18.628904+00:00 app[web.1]: result = await app(self.scope, self.receive, self.send)
2020-09-08T03:44:18.628904+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2020-09-08T03:44:18.628904+00:00 app[web.1]: return await self.app(scope, receive, send)
2020-09-08T03:44:18.628905+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
2020-09-08T03:44:18.628905+00:00 app[web.1]: await super().__call__(scope, receive, send)
2020-09-08T03:44:18.628905+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
2020-09-08T03:44:18.628906+00:00 app[web.1]: await self.middleware_stack(scope, receive, send)
2020-09-08T03:44:18.628906+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
2020-09-08T03:44:18.628907+00:00 app[web.1]: raise exc from None
2020-09-08T03:44:18.628907+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
2020-09-08T03:44:18.628908+00:00 app[web.1]: await self.app(scope, receive, _send)
2020-09-08T03:44:18.628908+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
2020-09-08T03:44:18.628908+00:00 app[web.1]: raise exc from None
2020-09-08T03:44:18.628909+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
2020-09-08T03:44:18.628909+00:00 app[web.1]: await self.app(scope, receive, sender)
2020-09-08T03:44:18.628910+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
2020-09-08T03:44:18.628910+00:00 app[web.1]: await route.handle(scope, receive, send)
2020-09-08T03:44:18.628910+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
2020-09-08T03:44:18.628911+00:00 app[web.1]: await self.app(scope, receive, send)
2020-09-08T03:44:18.628911+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
2020-09-08T03:44:18.628912+00:00 app[web.1]: response = await func(request)
2020-09-08T03:44:18.628912+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
2020-09-08T03:44:18.628912+00:00 app[web.1]: raw_response = await run_endpoint_function(
2020-09-08T03:44:18.628913+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
2020-09-08T03:44:18.628913+00:00 app[web.1]: return await dependant.call(**values)
2020-09-08T03:44:18.628914+00:00 app[web.1]: File "/app/main.py", line 61, in TrackDownload
2020-09-08T03:44:18.628914+00:00 app[web.1]: return await harmonoidService.TrackDownload(track_id, album_id, track_name)
2020-09-08T03:44:18.628914+00:00 app[web.1]: File "/app/harmonoidservice/downloading.py", line 77, in TrackDownload
2020-09-08T03:44:18.628915+00:00 app[web.1]: await self.SaveMetaData(trackInfo)
2020-09-08T03:44:18.628915+00:00 app[web.1]: File "/app/harmonoidservice/downloading.py", line 29, in SaveMetaData
2020-09-08T03:44:18.628916+00:00 app[web.1]: await audioFile.init()
2020-09-08T03:44:18.628916+00:00 app[web.1]: File "/app/harmonoidservice/async_mutagen.py", line 11, in init
2020-09-08T03:44:18.628916+00:00 app[web.1]: await loop.run_in_executor(None, super().__init__, self.filename)
2020-09-08T03:44:18.628917+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2020-09-08T03:44:18.628917+00:00 app[web.1]: result = self.fn(*self.args, **self.kwargs)
2020-09-08T03:44:18.628918+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/mutagen/_file.py", line 48, in __init__
2020-09-08T03:44:18.628918+00:00 app[web.1]: self.load(*args, **kwargs)
2020-09-08T03:44:18.628918+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/mutagen/_util.py", line 154, in wrapper
2020-09-08T03:44:18.628919+00:00 app[web.1]: with _openfile(self, filething, filename, fileobj,
2020-09-08T03:44:18.628919+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/contextlib.py", line 113, in __enter__
2020-09-08T03:44:18.628920+00:00 app[web.1]: return next(self.gen)
2020-09-08T03:44:18.628920+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/mutagen/_util.py", line 272, in _openfile
2020-09-08T03:44:18.628920+00:00 app[web.1]: raise MutagenError(e)
2020-09-08T03:44:18.628921+00:00 app[web.1]: mutagen.MutagenError: [Errno 2] No such file or directory: '3pQLMqRn_pw.m4a'
```
I have literally no idea, what is wrong here.

**Comment by mytja** [comment]
This works, but some of my old songs won't work from migration to YT Music.
harmonoid-us is going to stay spotify server...

**Comment by alexmercerind** [comment]
Hi @mytja !
Thanks for the [harmonoid-us](http://harmonoid-us.herokuapp.com).

**Comment by raitonoberu** [comment]
Looks like youtube-dl couldn't download the video.
IDK why but harmonoid-ru works fine
http://harmonoid-ru.herokuapp.com/trackdownload?track_id=3pQLMqRn_pw&album_id=MPREb_cK4MowB5Oy6

**Comment by raitonoberu** [comment]
Anyway, try to redeploy the backend.

**Comment by alexmercerind** [comment]
I think I should enable logs of youtube-dl for the debugging. 
Seems, YouTube server will need a lot more baby-sitting.

**Comment by alexmercerind** [comment]
And I forgot to ask you guys... 😅

@raitonoberu & @mytja,

I wanna say... If you want to add any accent colors of your choice, let me know in this thread. 👌
Since, I'm very strictly following material design guidelines, I picked current colors from [this](https://material.io/design/color/the-color-system.html) site under the section **"2014 Material Design color palettes"** (You can choose colors from here).
🌈 So, give me your favorite colors (a light shade & a dark shade of each).

**Comment by raitonoberu** [comment]
You already added my favorite colors. It would be great if you also added a cyan color (#80CBC4 and #00695C i guess)

Thanks a lot!

**Comment by mytja** [comment]
I'm not a pro designer, but I'll see what I can do

**Comment by alexmercerind** [comment]
@mytja 😂 Yeah, I'm also not a designer (not even front-end guy), that's why I'm just following the material design documentation (Because if I design myself, then it is always horrible). 
This project still is more of a back-end, as I have to write more code about searching/saving/deleting/browsing than of colors/UI.
I'm just learning, I'm 0% pro in this.

**Comment by mytja** [comment]
I think this could look nice
#0D47A1
Body: #82B1FF

**Comment by alexmercerind** [comment]
Yeah @mytja,
I also want artist searching (I already added it's button but it is currently commented out off the code), but I always end up fixing other bugs and improving performance (e.g. Now you should no longer see progress bar when you tap on a album in your collection, now its tracks are cached in memory when you refresh the collection).

I'm also being kinda lazy, so let's see when I add artist search (probably v0.0.3).

**Comment by MickLesk** [comment]
i've forked the project and improve the translation, do you want to check out?

**Comment by alexmercerind** [comment]
@MickLesk yeah! Why not. I'm just waiting. Take care of things like capitalization of letters etc.
Make a new PR 😉.
